config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/about'
  get 'pages/team'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="is-preload">

    		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><%= link_to "Index", pages_index_path %></li>
							<li><%= link_to "About", pages_about_path %></li>
							<li><%= link_to "Team", pages_team_path %></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">
						<div class="inner">
							<%= yield %>							
						</div>
					</div>

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">		
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>


        
  </body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Acabo de modificar ABOUT</p>

app/views/pages/index.html.erb
<h1>Indice de la página</h1>
<p>Acabo de modificar el archivo app/views/pages/index.html.erb</p>
<h2>Hola Mundo!</h2>
©Copyright <%= Time.now.year%>



<% if Time.now.year >=2018 %>
    <p> Version 2.0 </p>
<% else %>
    <p> Version 1.0 </p>
<% end %>

app/views/pages/team.html.erb
<h1>contenido de la página team.html.erb</h1>

<%= image_tag 'gatito.jpg', class: 'hello', id: 'main-bg', alt: 'Hello photo'%>